#define A ".-"
#define B "-.."
#define C "-.-."
#define D "-.."
#define E "."
#define F "..-."
#define G "--."
#define H "...."
#define I ".."
#define J ".---"
#define K "-.-"
#define L ".-.."
#define M "--"
#define N "-."
#define O "---"
#define P ".--."
#define Q "--.-"
#define R ".-."
#define S "..."
#define T "-"
#define U "..-"
#define V "...-"
#define W ".--"
#define X "-..-"
#define Y "-.--"
#define Z "--.."

#define TO "- ---"
#define ME "-- ."
#define MOM "-- --- --"

#define NOW "-. --- .--"
#define DOT "-.. --- -"
#define DOG "-.. --- --."
#define CAT "-.-. .- -"
#define DAD "-.. .- -.."

#define TOM "- --- --"
#define WILSON ".-- .. .-.. ... --- -."
#define DIMA "-.. .. -- .- "
#define KOSTYA "-.- --- ... - -.-- .-"

#define FISH "..-. .. ... ...."
#define PICO ".--. .. -.-. ---"
#define ALARM ".- .-.. .- .-. --"

#define IRELAND ".. .-. . .-.. .- -. -.."
#define TRINITY "- .-. .. -. .. - -.--"
#define COLLEGE "-.-. --- .-.. .-.. . --. ."



#define ZERO "-----"
#define ONE ".----"
#define TWO "..---"
#define THREE "...--"
#define FOUR "....-"
#define FIVE "....."
#define SIX "-...."
#define SEVEN "--..."
#define EIGHT "---.."
#define NINE "----."
